### PR TITLE
feat(ui): Add dummy `HomeScreen`

### PR DESCRIPTION
**Pull request by T0ffik**

### CODE REVIEW

**Review by Veryyapeee — APPROVED** [review]

**Review by maciejopalinski — CHANGES_REQUESTED** [review]
Is it temporary, work in progress or something? I don't understand why @Veryyapeee approved this PR as it doesn't add anything. If this is still work in progress you should convert it to a draft pull request. Implement `HomeScreen` here when you finish your Figma design.

**Comment by maciejopalinski** [comment]
And one more thing. I think that you should rename your `HomeScreen` component to `HomePage` and put it in `/src/pages` instead of `/src/components`.
I assume that components are meant to be reusable but pages are not reusable as they include hard coded content. So they should be in separate directory for cleaner project structure.
Let me know if this is correct @Veryyapeee 

Something like MovieTitle is very reusable as it gets for example title and image url parameter, so it is a component.
But HomePage is not reusable, it does not get any params so it is a page and should be put in separate directory from reusable components.

**Comment by Veryyapeee** [comment]
> Is it temporary, work in progress or something? I don't understand why @Veryyapeee approved this PR as it doesn't add anything. If this is still work in progress you should convert it to a draft pull request. Implement `HomeScreen` here when you finish your Figma design.

Scope of the task was to just implement a blank div that we can inject to code (read AC on trello), these easy tasks are there for team to gest familliar with components etc.

But yea, my bad, it soulem be draft, the task description says that it nas to be connected to routing, so it's waiting for PR with routing

Also +1 for comment about the /Pages folder
Naming in JS is irrevelant, but I thing it shoud be /screens folder

Generally convention is:
-Client Side Rendering - screens
-Server Side Rendering - Pages

**Comment by Veryyapeee** [comment]
> Is it temporary, work in progress or something? I don't understand why @Veryyapeee approved this PR as it doesn't add anything. If this is still work in progress you should convert it to a draft pull request. Implement `HomeScreen` here when you finish your Figma design.

Yea, correct, that's the purpose of components itself.

Go with /screens, I described that in previous comment

And yea, screens are not reusable

If someone nas hard time with wrapping his head around that concept, i recommend to read something about Atomic Design React ~ easy concept that could explain most of these things :D

**Review by maciejopalinski — APPROVED** [review]
Everything seems fine!

**Pull request merged**
