### PR TITLE
chore: Ignore VSCode workspace files

### PR DESCRIPTION
**Pull request by maciejopalinski**

### CODE REVIEW

**Comment by Veryyapeee** [comment]
I was going to configure the .gitignore file tonight, thanks for doing my job 8)

**Review by Veryyapeee — APPROVED** [review]

**Comment by maciejopalinski** [comment]
@Veryyapeee I cannot merge this PR. It says that I need 2 approving reviews. Can you change that or am I doing something wrong?

**Comment by Veryyapeee** [comment]
Yea, every PR needs 2 approvals and all checks passed to be merged, at this point I actually wanted to do that so as an admin I'll merge it for you :P

**Comment by maciejopalinski** [comment]
@Veryyapeee Ok thanks. All clear!

**Pull request merged**
