### PR TITLE
fix(deps): Update all packages

### PR DESCRIPTION
**Pull request by maciejopalinski**
(reopened pull request)

NPM did this. If the CI won't pass... don't blame me lol
This is not updating packages, this cannot fail, right...?

### CODE REVIEW

**Comment by maciejopalinski** [comment]
Yoooo @Veryyapeee GitHub Actions works!

And I just realized that I could just merge your changes from main to fix/npm without reopening pull request, but...

**Comment by Veryyapeee** [comment]
Cool, don't blame me for npm ci instead of npmj install in workflow, I did it like at 1am xD
I think that's the last update packages PR that we should do, in like short terms projects and we are not up to date with technologies generally we shouldn't do that, and it's not beneficial
Approved for now, pls if you need one more approve, mention this on DC

**Comment by maciejopalinski** [comment]
And updating packages now worked too!

What I learned throughout all of this nightmare:
* GitHub Actions will not magically get your new config if it is on a different branch. Just update your branch!
* There is no need for reopening pull requests. Just merge the changes from more significant branch.
* Before you push and wait for checks, check it by yourself running: `npm clean-install && npm build && npm test`, because this is what GitHub Actions does... lol

**Comment by maciejopalinski** [comment]
And btw, the packages are just updated to the requirements in package.json. Only compatible updates, only major changes. It is safe, trust me.

**Review by Veryyapeee — APPROVED** [review]

**Review by Mariusz-web — APPROVED** [review]

**Pull request merged**
