### PR TITLE
Add footer.scss styles

### PR DESCRIPTION
**Pull request by Mariusz-web**

### CODE REVIEW

**Comment by Mariusz-web** [comment]
Waiting for approve in #17 which will solve the issue from checks

**Comment by Mariusz-web** [comment]
Ready for review

**Review by Veryyapeee — CHANGES_REQUESTED** [review]
This should be merged after merge with BaseScreen so you can connect the footer, and we would see how it's actually looks like

**Comment by Veryyapeee** [comment]
@Mariusz-web The BaseScreen is on main, so you can go ahead and connect your footer to main screen :P

**Review by Veryyapeee — APPROVED** [review]

**Review by Veryyapeee — APPROVED** [review]

**Review by N00BKU — APPROVED** [review]

**Pull request merged**
